-- NOTE: disabled for now
return {}

-- return {
--   "nvim-orgmode/orgmode",
--   event = "VeryLazy",
--   opts = {
--     org_agenda_files = "~/orgfiles/**/*",
--     org_default_notes_file = "~/orgfiles/refile.org",
--     ui = {
--       menu = {
--         handler = function(data)
--           -- your handler here, for example:
--           local options = {}
--           local options_by_label = {}
--
--           for _, item in ipairs(data.items) do
--             -- Only MenuOption has `key`
--             -- Also we don't need `Quit` option because we can close the menu with ESC
--             if item.key and item.label:lower() ~= "quit" then
--               table.insert(options, item.label)
--               options_by_label[item.label] = item
--             end
--           end
--
--           local handler = function(choice)
--             if not choice then
--               return
--             end
--
--             local option = options_by_label[choice]
--             if option.action then
--               option.action()
--             end
--           end
--
--           vim.ui.select(options, {
--             prompt = data.prompt,
--           }, handler)
--         end,
--       },
--     },
--   },
-- }
